### ISSUE TITLE
Moving anchor should be allowed to go off-screen

### ISSUE THREAD

**Issue by vendethiel** [slaren/GladiusEx#19]
![](https://imgur.com/a/58Jmb0d)

**Comment by slaren** [comment]
This should be what you want to change:

https://github.com/slaren/GladiusEx/blob/5abcb560c0e4a8f25a192e92e2904cff699d15b3/GladiusEx.lua#L1391

**Comment by vendethiel** [comment]
It's a bit dangerous if you have two screens (you can drag it off the edge of the screen) but it should be fine for now.

**Comment by vendethiel** [comment]
Fixed as part of 9dd2f0ba9425fac5d8d058451a4621b209c82ad3
