### ISSUE TITLE
Do talent detection

### ISSUE THREAD

**Issue by vendethiel** [slaren/GladiusEx#3]
https://mods.curse.com/addons/wow/libgroupinspect

We might need to manually enter data points (spell id => position in the tree, I mean).

Not sure how to detect PVP talents.

**Comment by vendethiel** [comment]
I just realized we have it as a dependency already, it's just seemingly unused.

**Comment by slaren** [comment]
It's used here:
https://github.com/slaren/GladiusEx/blob/bb125ef5889780098b202b951f3d38da5e69c275/GladiusEx.lua#L361
https://github.com/slaren/GladiusEx/blob/bb125ef5889780098b202b951f3d38da5e69c275/GladiusEx.lua#L808-L815

**Comment by vendethiel** [comment]
Oh, alright.
Guess I can try to bend LibCooldownTracker to force-detect a spell. I can probably make this more generic:

https://github.com/vendethiel/LibCooldownTracker-10/blob/master/library.lua#L461

I'm just not sure how I should "un-detect" when someone specs out of a spell. Sounds tough.

Also TIL github does that.

**Comment by slaren** [comment]
I used the "copy permalink" option in the three dots button and just pasted that link here.

**Comment by vendethiel** [comment]
https://github.com/vendethiel/LibCooldownTracker-10/blob/f703b7d40530f114f918f9d1b08bfc1909b73814/library.lua#L461

**Comment by vendethiel** [comment]
Okay, well, I'm not sure how that works.

**Comment by slaren** [comment]
https://github.com/vendethiel/LibCooldownTracker-10/blob/f703b7d40530f114f918f9d1b08bfc1909b73814/library.lua#L461

I guess it only works for this repository ?

**Comment by vendethiel** [comment]
Looks like it. Thanks for checking

**Comment by vendethiel** [comment]
Even though it isn't documented as such on e.g. wow.amepedia, it seems [`GetPvpTalentInfo` can use inspect data](https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/TalentFrameBase.lua#L219)

**Comment by vendethiel** [comment]
will probably have to fork LibGroupInSpecT, [since the maintainer seems a bit inactive](https://www.wowace.com/projects/libgroupinspect/issues/14) and there's no repo on GH.

**Comment by vendethiel** [comment]
From:
https://github.com/tomrus88/BlizzardInterfaceCode/blob/c9d5cf53f3165beb2850dfde793d531e4b9dbaec/Interface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua#L75-L76

It seems that the `GetActiveSpecGroup(true)` hack I used (as `GetActiveTalentGroup`) for [wotlk addons](https://github.com/vendethiel/wotlk-partyabilitybars/blob/master/PAB.lua#L869) is still needed..

**Comment by vendethiel** [comment]
my hacked-on version of LibGroupInSpecT does primitive pvp detection, but the maintainer doesn't seem to check wowace often. Not sure what to do yet, might end up forking the lib...

The basics work tho, talent detection works correctly. I also added LibFunctional to LibCT, just to make it easier to manipulate the data (here, remove the previously-detected talents).
